apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: tools
  name: tools
spec:
  replicas: 1
  selector:
    app: tools
    deploymentconfig: tools
  strategy:
    resources: {}
    rollingParams:
    type: Rolling
  template:
    metadata:
      labels:
        app: tools
        deploymentconfig: tools
    spec:
      containers:
      - command: ["/bin/sh", "-ec", "touch /tmp/healthy; while :;do true; sleep 10; done"]
        env:
        - name: KUBECONFIG
          value: /tmp/kubecfg
        image: 'docker-registry.default.svc:5000/prepare/openshift-cli:3.11b'
        imagePullPolicy: Always
        name: tools
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
            failureThreshold: 2
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
            failureThreshold: 2
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 100Mi
            requests:
              memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange