apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: gitops-deployer
  name: gitops-deployer
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: 'gitops-deployer:latest'
  source:
    git:
      uri: 'https://bitbucket.org/erik-lund/exercise-8e.git'
    sourceSecret:
      name: sa-lab-rh
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk-11-rhel7:latest'
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - generic:
        secret: suydfiasfasifaenifsf
      type: Generic
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitops-deployer
  name: gitops-deployer
spec:
  lookupPolicy:
    local: true
