apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: tools
  name: tools
spec:
  replicas: 0
  selector:
    app: tools
    deploymentconfig: tools
  strategy:
    resources: {}
    rollingParams:
    type: Rolling
  template:
    metadata:
      labels:
        app: tools
        deploymentconfig: tools
    spec:
      containers:
      - command: ["/bin/sh", "-ec", "while :;do true; sleep 10; done"]
        env:
        - name: KUBECONFIG
          value: /tmp/kubecfg
        image: widerin/openshift-cli:v3.11.0
        imagePullPolicy: Always
        name: tools
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 200Mi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
